# This file was generated by GoReleaser. DO NOT EDIT.
cask "sme" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "14c29adee4529f1ba4e5f9d2fdf97e9faec23e6d258e90a154eed928a879213e"
      url "https://github.com/syncmyenv/core/releases/download/v#{version}/sme_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b028cca2326bf767834f0262413ad9206930c392b68837a59dc4c662fc877cb1"
      url "https://github.com/syncmyenv/core/releases/download/v#{version}/sme_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1bcfa9ac5fd0b6a91af191c1fe69582d71880ceb2364c35dce12cdb1d3375b30"
      url "https://github.com/syncmyenv/core/releases/download/v#{version}/sme_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d686bd18347c7e9ade42a464bab1719e22b7c663938bf643a04d7b2f0a62e11"
      url "https://github.com/syncmyenv/core/releases/download/v#{version}/sme_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sme"
  desc "Local-first, end-to-end encrypted backup, versioning and sync for .env files"
  homepage "https://syncmyenv.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sme"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sme"]
    end
  end

  # No zap stanza required
end
