# This file was generated by GoReleaser. DO NOT EDIT.
cask "sme" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "49585cbe951173ce3698b55272150d7a2fa87869f82efa0c4945fb88476907a9"
      url "https://github.com/syncmyenv/core/releases/download/v#{version}/sme_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a9cf8bbadefddf2e887e935e2c15f44d79c136d3099a2217638b8f8253d33d8"
      url "https://github.com/syncmyenv/core/releases/download/v#{version}/sme_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c901f5a0c5afa38a6745f75ee052ab2c9e366f04bf29208018e7f514d652bee"
      url "https://github.com/syncmyenv/core/releases/download/v#{version}/sme_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e84085ab2b0801ee5464d0e391e27ce44b1219b672bb72f2ac410e66b86a5c12"
      url "https://github.com/syncmyenv/core/releases/download/v#{version}/sme_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sme"
  desc "Local-first, end-to-end encrypted backup, versioning and sync for .env files"
  homepage "https://syncmyenv.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sme"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sme"]
    end
  end

  # No zap stanza required
end
